name: first workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: run first step
        run: echo welcome to githubactions
      - name: Multiline commands
        run: |
          echo "second line"
          echo "third line"
