name: Day1
on:
  push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: downloading or checking out code
        uses: actions/checkout@v4
      - name: started pushing
        
        run: echo started pushing
      - name: completed pushing
        run: |
          echo hi how are uses
          echo i'm fine
